### ISSUE TITLE
JsonLDObject default constructor depends on java.net.http.HttpClient

### ISSUE THREAD

**Issue by vitorpamplona** [decentralized-identity/jsonld-common-java#7]
I'd like to propose a clean up on the code to always create a `JsonLdOptions` with the currently used documentLoader passed as parameter `JsonLdOptions(jsonldObject.documentLoader)`. The goal is to avoid calling `SchemeRouter.defaultInstance()` on `JsonLdOptions`'s default constructor. That method has a direct dependency on `java.net.http.HttpClient` which doesn't exist on Android's Runtime. 

This also speeds things up a bit for anyone using custom DocumentLoaders by never creating the default instance just to replace it with the custom one. 

[Here](https://github.com/decentralized-identity/jsonld-common-java/blob/cfc4e0fce0ef1d3e62bb37cf5363375880414513/src/main/java/foundation/identity/jsonld/JsonLDObject.java#L288)'s an example. Android developers need to override this method, going from

```java
        JsonLdOptions options = new JsonLdOptions();
        if (this.getDocumentLoader() != null) {
            options.setDocumentLoader(this.getDocumentLoader());
        }
``` 
to
```java
        JsonLdOptions options = new JsonLdOptions(this.getDocumentLoader());
```

I actually don't know why this test exists: `this.getDocumentLoader() != null`, since the only way for the `documentLoader` to be null is if somebody manually set that to null, which seems weird.

**Comment by peacekeeper** [comment]
@vitorpamplona Sorry for late reponse.. This makes sense to me, do you want to create a PR to make that change?

**Comment by peacekeeper** [comment]
@vitorpamplona I think this should be fixed. Better late then never :)
